package com.moonkata.flonovel.desktop.sync

import com.moonkata.flonovel.desktop.library.CredentialsStore
import org.json.JSONObject
import java.nio.charset.StandardCharsets
import java.security.SecureRandom

/**
 * Manages the Supabase secret synchronization via Dropbox App Folder.
 *
 * Location: /.flonovel/secret.json (release) or /.flonovel/secret-dev.json (dev)
 *
 * Rules:
 * - C1: Secret is generated by machine (24 cryptographically random bytes), never human-typed.
 * - C2: No QR code pairing.
 * - C3: Never arbitrarily delete or recreate secret.
 * - C4: Regeneration only through explicit user action with severe warning:
 *       "기존 원격 기록에 접근할 수 없게 됩니다"
 * - C5: Never log or print the secret.
 * - C6: Stored separated in credentials.json.
 */
class SecretManager(
    private val dropboxClient: DropboxClient,
    private val credentialsStore: CredentialsStore,
    val secretFileName: String = DropboxConfig.secretFileName,
) {
    private val remotePath = "/.flonovel/$secretFileName"

    /**
     * Returns locally cached secret if available.
     */
    fun getCachedSecret(): String? =
        credentialsStore.load().cachedSupabaseSecret

    /**
     * Resolves the Supabase secret from local cache or Dropbox.
     * If not found on Dropbox, generates 24 random bytes, stores to Dropbox and credentials.json.
     * Never overwrites or recreates on network errors.
     */
    fun fetchOrInitializeSecret(): String? {
        val cached = credentialsStore.load().cachedSupabaseSecret
        if (!cached.isNullOrBlank()) {
            return cached
        }

        if (!dropboxClient.isLinked) {
            return null
        }

        // Try downloading existing secret from Dropbox
        val remoteBytes = dropboxClient.downloadFile(remotePath)
        if (remoteBytes != null) {
            val secret = parseSecret(remoteBytes)
            if (!secret.isNullOrBlank()) {
                credentialsStore.update { it.copy(cachedSupabaseSecret = secret) }
                return secret
            }
        }

        // If file does not exist on remote, generate a fresh 24-byte secret
        val generatedSecret = generate24ByteSecretHex()
        val jsonContent = JSONObject().apply {
            put("secret", generatedSecret)
            put("createdAt", System.currentTimeMillis())
        }.toString(2)

        val uploadResult = dropboxClient.uploadFile(
            path = remotePath,
            content = jsonContent.toByteArray(StandardCharsets.UTF_8),
            overwrite = false,
        )

        if (uploadResult is DropboxUploadResult.Success) {
            credentialsStore.update { it.copy(cachedSupabaseSecret = generatedSecret) }
            return generatedSecret
        }

        // If upload failed, check if remote was created concurrently
        val retryBytes = dropboxClient.downloadFile(remotePath)
        if (retryBytes != null) {
            val secret = parseSecret(retryBytes)
            if (!secret.isNullOrBlank()) {
                credentialsStore.update { it.copy(cachedSupabaseSecret = secret) }
                return secret
            }
        }

        return null
    }

    /**
     * Recreates the secret upon EXPLICIT user confirmation.
     * Overwrites remote secret and updates local credentials.json.
     */
    fun regenerateSecret(): String? {
        if (!dropboxClient.isLinked) {
            return null
        }

        val newSecret = generate24ByteSecretHex()
        val jsonContent = JSONObject().apply {
            put("secret", newSecret)
            put("createdAt", System.currentTimeMillis())
        }.toString(2)

        val uploadResult = dropboxClient.uploadFile(
            path = remotePath,
            content = jsonContent.toByteArray(StandardCharsets.UTF_8),
            overwrite = true,
        )

        if (uploadResult is DropboxUploadResult.Success) {
            credentialsStore.update { it.copy(cachedSupabaseSecret = newSecret) }
            return newSecret
        }

        return null
    }

    private fun generate24ByteSecretHex(): String {
        val bytes = ByteArray(24)
        SecureRandom().nextBytes(bytes)
        return bytes.joinToString("") { "%02x".format(it) }
    }

    private fun parseSecret(content: ByteArray): String? = runCatching {
        val str = String(content, StandardCharsets.UTF_8)
        val json = JSONObject(str)
        json.optString("secret", null)
    }.getOrNull()
}
