package com.moonkata.flonovel.desktop.preprocess

import com.moonkata.flonovel.desktop.text.EncodingDetector
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.name
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Pins the preprocessor's output byte for byte, so the Android port can be held to the same bytes
 * (AGENTS.md §1: both apps must produce identical output from the same fixtures, or two devices
 * rewrite the same book differently and conflict copies pile up).
 *
 * The expectations are generated by this app: `./gradlew test -PupdateGolden`, then copy
 * `fixtures/parity/` to the Android app's test resources. The last test fails until the copies match.
 */
class PreprocessParityTest {

    private val dir: Path = Path.of("src/test/resources/fixtures/parity")
    private val updateGolden = System.getProperty("flonovel.updateGolden") == "true"

    private fun inputs(): List<Path> = Files.list(dir).use { s ->
        s.filter { it.name.endsWith(".input.txt") }.sorted().toList()
    }

    private fun expectedFor(input: Path): Path = input.resolveSibling(input.name.removeSuffix(".input.txt") + ".expected.txt")

    private fun preprocess(bytes: ByteArray): ByteArray =
        TextPreprocessor.normalizeContent(EncodingDetector.decode(bytes)).toByteArray(Charsets.UTF_8)

    private fun check(expectedFile: Path, actual: ByteArray) {
        if (updateGolden) {
            Files.write(expectedFile, actual)
            return
        }
        assertTrue(Files.exists(expectedFile), "Missing $expectedFile; run ./gradlew test -PupdateGolden")
        assertEquals(
            Files.readAllBytes(expectedFile).toString(Charsets.UTF_8),
            actual.toString(Charsets.UTF_8),
            "Preprocessed output of ${expectedFile.name} changed",
        )
    }

    @Test
    fun contentMatchesExpectedBytes() {
        val files = inputs()
        assertTrue(files.size >= 8)
        for (input in files) check(expectedFor(input), preprocess(Files.readAllBytes(input)))
    }

    @Test
    fun expectedOutputIsAFixedPoint() {
        if (updateGolden) return
        for (input in inputs()) {
            val once = Files.readAllBytes(expectedFor(input))
            assertEquals(once.toString(Charsets.UTF_8), preprocess(once).toString(Charsets.UTF_8), "${input.name} is not idempotent")
        }
    }

    @Test
    fun fileNamesMatchExpected() {
        val names = Files.readAllLines(dir.resolve("filenames.input.tsv"), Charsets.UTF_8)
        val cleaned = names.joinToString("") { TextPreprocessor.cleanFileName(it) + "\n" }
        check(dir.resolve("filenames.expected.tsv"), cleaned.toByteArray(Charsets.UTF_8))
    }

    /** The Android app holds a copy; if either side changes alone, the two apps drift apart. */
    @Test
    fun androidCopyIsIdentical() {
        if (updateGolden) return
        val android = Path.of("../FloNovel-android/app/src/test/resources/fixtures/parity")
        assertTrue(Files.isDirectory(android), "Missing $android")
        fun names(d: Path) = Files.list(d).use { s -> s.map { it.name }.filter { !it.startsWith(".") }.sorted().toList() }
        val ours = names(dir)
        val theirs = names(android)
        assertEquals(ours, theirs)
        for (name in ours) {
            assertTrue(
                Files.readAllBytes(dir.resolve(name)).contentEquals(Files.readAllBytes(android.resolve(name))),
                "$name differs between the Desktop and Android fixtures",
            )
        }
    }
}
