package com.moonkata.flonovel.android.data.preprocess

import com.moonkata.flonovel.android.data.file.EncodingDetector
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Holds the phone's preprocessor to the Desktop's output, byte for byte, on the fixtures in
 * `fixtures/parity/` (generated by the Desktop app; see its PreprocessParityTest). Runs on the
 * JVM; PreprocessParityDeviceTest repeats the content check on Android's own regex engine.
 */
class PreprocessParityTest {

    private val dir = File(requireNotNull(javaClass.classLoader?.getResource("fixtures/parity")) { "fixtures/parity missing" }.toURI())

    private fun inputs() = dir.listFiles { f -> f.name.endsWith(".input.txt") }!!.sortedBy { it.name }

    private fun preprocess(bytes: ByteArray): ByteArray =
        TextPreprocessor.normalizeContent(EncodingDetector.decode(bytes)).toByteArray(Charsets.UTF_8)

    @Test
    fun contentMatchesTheDesktopByteForByte() {
        val files = inputs()
        assertTrue(files.size >= 8)
        for (input in files) {
            val expected = File(dir, input.name.removeSuffix(".input.txt") + ".expected.txt").readBytes()
            assertEquals(
                "${input.name} differs from the Desktop output",
                expected.toString(Charsets.UTF_8),
                preprocess(input.readBytes()).toString(Charsets.UTF_8),
            )
        }
    }

    @Test
    fun outputIsAFixedPoint() {
        for (input in inputs()) {
            val once = preprocess(input.readBytes())
            assertArrayEquals("${input.name} is not idempotent", once, preprocess(once))
        }
    }

    @Test
    fun fileNamesMatchTheDesktop() {
        val names = File(dir, "filenames.input.tsv").readLines(Charsets.UTF_8)
        val cleaned = names.joinToString("") { TextPreprocessor.cleanFileName(it) + "\n" }
        assertEquals(File(dir, "filenames.expected.tsv").readText(Charsets.UTF_8), cleaned)
    }

    /** The Desktop app holds the original; if either side changes alone, the apps drift apart. */
    @Test
    fun desktopCopyIsIdentical() {
        // Unit tests run with the app module as the working directory.
        val desktop = File("../../FloNovel-desktop/src/test/resources/fixtures/parity")
        assertTrue("Missing ${desktop.path}", desktop.isDirectory)
        // Dot-files are left out: Gradle's default excludes drop .gitattributes from resources.
        fun names(d: File) = d.listFiles()!!.map { it.name }.filterNot { it.startsWith(".") }.sorted()
        val ours = names(dir)
        assertEquals(ours, names(desktop))
        for (name in ours) {
            assertArrayEquals("$name differs between the Android and Desktop fixtures", File(dir, name).readBytes(), File(desktop, name).readBytes())
        }
    }

    @Test
    fun fullWidthDigitsAreNotHeadings() {
        // ICU's \d would match these; the JVM's does not, so neither may the port.
        assertEquals("제１２화 본문", TextPreprocessor.normalizeHeadings("제１２화 본문"))
        assertEquals("## 제12화 본문", TextPreprocessor.normalizeHeadings("제12화 본문"))
    }
}
